<a href="https://colab.research.google.com/github/Santibareiro27/Inteligencia-Computacional/blob/main/RA1_LAB1/Datos_Laboratorio_N%C2%B01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Datos - Laboratorio N°1

In [ ]:
# Importación, visualización, manipulación de datos
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

## Experiencia 1

In [ ]:
# Archivos pueden arrastrarse al área de trabajo o procesarse en local

# Version Online
!wget https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/acv/datos_acv.zip

--2026-03-31 15:01:41--  https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/acv/datos_acv.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/acv/datos_acv.zip [following]
--2026-03-31 15:01:41--  https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/acv/datos_acv.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65545 (64K) [application/zip]
Saving to: ‘datos_acv.zip’

datos_acv.zip       100%[===================>]  64.01K  --.-KB/s    in 0.04s

2026-03-31 15:01:42 (1.59 MB/s) - ‘datos_acv.zip’ saved [65545/65545]

In [ ]:
!unzip datos_acv.zip

Archive:  datos_acv.zip
  inflating: datos_acv.csv

In [ ]:
# Lectura del dataset
dataset_acv = pd.read_csv("datos_acv.csv")
dataset_acv

,id,genero,edad,hipertension,enfermedad_corazon,casado_alguna_vez,tipo_trabajo,tipo_residencia,nivel_glucosa,imc,estado_fumador,apoplejia
0,9046,hombre,67.0,0,1,1,privado,urbano,228.69,36.6,fumaba,1
1,51676,mujer,61.0,0,0,1,autonomo,rural,202.21,NaN,nunca,1
2,31112,hombre,80.0,0,1,1,privado,rural,105.92,32.5,nunca,1
3,60182,mujer,49.0,0,0,1,privado,urbano,171.23,34.4,fuma,1
4,1665,mujer,79.0,1,0,1,autonomo,rural,174.12,24.0,nunca,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,mujer,80.0,1,0,1,privado,urbano,83.75,NaN,nunca,0
5106,44873,mujer,81.0,0,0,1,autonomo,urbano,125.20,40.0,nunca,0
5107,19723,mujer,35.0,0,0,1,autonomo,rural,82.99,30.6,nunca,0
5108,37544,hombre,51.0,0,0,1,privado,rural,166.29,25.6,fumaba,0
5109,44679,mujer,44.0,0,0,1,gubernamental,urbano,85.28,26.2,desconocido,0

## Experiencia 2

In [ ]:
# Archivos pueden arrastrarse al área de trabajo o procesarse en local

# Version Online
!wget https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/adl/datos_adl.zip

--2026-03-31 15:02:33--  https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/adl/datos_adl.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/adl/datos_adl.zip [following]
--2026-03-31 15:02:34--  https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/adl/datos_adl.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21527 (21K) [application/zip]
Saving to: ‘datos_adl.zip’

datos_adl.zip       100%[===================>]  21.02K  --.-KB/s    in 0.006s

2026-03-31 15:02:34 (3.64 MB/s) - ‘datos_adl.zip’ saved [21527/21527]

In [ ]:
!unzip datos_adl.zip

Archive:  datos_adl.zip
  inflating: datos_adl.csv

In [ ]:
# Lectura del dataset
dataset_adl = pd.read_csv("datos_adl.csv")
dataset_adl

      MQ2  MQ9  MQ135  MQ137  MQ138  MG-811  Situacion
0     670  696   1252   1720   1321    2431          4
1     641  674   1156   1652   1410    2433          4
2     642  646   1159   1643   1455    2361          4
3     640  590   1105   1608   1459    2427          4
4     616  627   1192   1637   1466    2447          4
...   ...  ...    ...    ...    ...     ...        ...
1840  862  826   1564   1768   1540    2037          4
1841  917  821   1571   1779   1543    2008          4
1842  925  832   1582   1776   1545    1989          4
1843  928  840   1587   1787   1538    1986          4
1844  926  840   1606   1785   1555    1996          4

[1845 rows x 7 columns]

## Experiencia 3

In [ ]:
# Archivos pueden arrastrarse al área de trabajo o procesarse en local

# Version Online
!wget https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/ccs/datos_ccs.zip

--2026-03-31 15:03:50--  https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/ccs/datos_ccs.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/ccs/datos_ccs.zip [following]
--2026-03-31 15:03:50--  https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/ccs/datos_ccs.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10017 (9.8K) [application/zip]
Saving to: ‘datos_ccs.zip’

datos_ccs.zip       100%[===================>]   9.78K  --.-KB/s    in 0.001s

2026-03-31 15:03:51 (11.6 MB/s) - ‘datos_ccs.zip’ saved [10017/10017]

In [ ]:
!unzip datos_ccs.zip

Archive:  datos_ccs.zip
  inflating: datos_ccs.csv

In [ ]:
# Lectura del dataset
dataset_ccs = pd.read_csv("datos_ccs.csv")
dataset_ccs

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

## Experiencia 4

In [ ]:
# Archivos pueden arrastrarse al área de trabajo o procesarse en local

# Version Online
!wget https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/bmd/datos_bmd.zip

--2026-03-31 15:04:39--  https://github.com/AxelSkrauba/applied-ai-engineering/raw/main/datasets/bmd/datos_bmd.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/bmd/datos_bmd.zip [following]
--2026-03-31 15:04:39--  https://raw.githubusercontent.com/AxelSkrauba/applied-ai-engineering/main/datasets/bmd/datos_bmd.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9939 (9.7K) [application/zip]
Saving to: ‘datos_bmd.zip’

datos_bmd.zip       100%[===================>]   9.71K  --.-KB/s    in 0.001s

2026-03-31 15:04:40 (11.3 MB/s) - ‘datos_bmd.zip’ saved [9939/9939]

In [ ]:
!unzip datos_bmd.zip

Archive:  datos_bmd.zip
  inflating: datos_bmd.csv

In [ ]:
# Lectura del dataset
dataset_bmd = pd.read_csv("datos_bmd.csv")
dataset_bmd

,Genero,Edad,CircunferenciaCabeza,AnchoHombro,AnchoPecho,Abdomen,Cintura,Cadera,LongitudBrazo,LongitudHombroCintura,LongitudCinturaRodilla,LongitudPierna,AlturaTotal
0,1.0,30,55.88,45.72,50.80,45.72,35.56,55.88,55.88,63.50,63.50,55.88,132.08
1,1.0,28,48.26,55.88,43.18,45.72,53.34,63.50,71.12,58.42,63.50,50.80,142.24
2,1.0,29,50.80,50.80,45.72,27.94,48.26,35.56,60.96,53.34,50.80,53.34,114.30
3,1.0,23,40.64,40.64,50.80,45.72,55.88,45.72,38.10,66.04,50.80,48.26,101.60
4,1.0,31,38.10,50.80,71.12,45.72,231.14,43.18,40.64,53.34,53.34,48.26,139.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2.0,2,45.72,38.10,20.32,50.80,48.26,50.80,35.56,33.02,27.94,45.72,81.28
712,2.0,10,53.34,30.48,30.48,55.88,60.96,66.04,53.34,38.10,35.56,63.50,114.30
713,2.0,13,55.88,15.24,35.56,63.50,45.72,76.20,53.34,50.80,40.64,83.82,149.86
714,2.0,4,50.80,38.10,25.40,50.80,50.80,53.34,45.72,25.40,30.48,48.26,93.98
715,2.0,9,50.80,33.02,27.94,53.34,60.96,27.94,55.88,35.56,38.10,63.50,111.76

## Experiencia 5

In [ ]:
# Dataset desde el repositorio en Drive

!wget -c --no-check-certificate "https://drive.google.com/uc?export=download&id=1bRvDjRE5AJzJ4MqMGlPbcA0nn8Vgi7Vl&confirm=t" -O Audio_clasificar.zip

--2026-03-31 15:09:11--  https://drive.google.com/uc?export=download&id=1bRvDjRE5AJzJ4MqMGlPbcA0nn8Vgi7Vl&confirm=t
Resolving drive.google.com (drive.google.com)... 64.233.188.139, 64.233.188.113, 64.233.188.101, ...
Connecting to drive.google.com (drive.google.com)|64.233.188.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1bRvDjRE5AJzJ4MqMGlPbcA0nn8Vgi7Vl&export=download [following]
--2026-03-31 15:09:12--  https://drive.usercontent.google.com/download?id=1bRvDjRE5AJzJ4MqMGlPbcA0nn8Vgi7Vl&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.170.132, 2404:6800:4008:c19::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.170.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1066960 (1.0M) [application/octet-stream]
Saving to: ‘Audio_clasificar.zip’

Audio_clasificar.zi 100%[===================>]   1.02M  --.-KB/s    in 0.009s

2026-03-31 15:09:14 (119 MB/s) - ‘Audio_clasificar.zip’ saved [1066960/1066960]

In [ ]:
!unzip Audio_clasificar.zip

Archive:  Audio_clasificar.zip
  inflating: Audio_clasificar.wav

In [ ]:
# Librerías básicas para audio
import scipy.io.wavfile as waves
from IPython.display import Audio

In [ ]:
archivo = 'Audio_clasificar.wav'
fs, todo = waves.read(archivo)


print("Frecuencia de muestreo: ", fs)
print("Muestras: ", todo.shape)   # Tamaño del vector, cantidad de muestras temporales

Frecuencia de muestreo:  24000
Muestras:  (605779,)

In [ ]:
# Reproducir el Audio
Audio(todo, rate=fs)

In [ ]:
# Audio: ambiente_largo, para la inferencia luego del modelado...
!wget -c --no-check-certificate "https://drive.google.com/uc?export=download&id=1vi6VQpdAr1M67gFu5QK6DNvtWBtEFlcl&confirm=t" -O ambiente_largo.wav

--2026-03-31 15:13:10--  https://drive.google.com/uc?export=download&id=1vi6VQpdAr1M67gFu5QK6DNvtWBtEFlcl&confirm=t
Resolving drive.google.com (drive.google.com)... 74.125.203.101, 74.125.203.139, 74.125.203.113, ...
Connecting to drive.google.com (drive.google.com)|74.125.203.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1vi6VQpdAr1M67gFu5QK6DNvtWBtEFlcl&export=download [following]
--2026-03-31 15:13:10--  https://drive.usercontent.google.com/download?id=1vi6VQpdAr1M67gFu5QK6DNvtWBtEFlcl&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.170.132, 2404:6800:4008:c19::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.170.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 46083500 (44M) [audio/wav]
Saving to: ‘ambiente_largo.wav’

ambiente_largo.wav  100%[===================>]  43.95M  39.1MB/s    in 1.1s

2026-03-31 15:13:14 (39.1 MB/s) - ‘ambiente_largo.wav’ saved [46083500/46083500]